# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24)),
                ('full_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='weddingpicture',
            name='picture',
            field=models.ImageField(upload_to=b'weddingpictures/%Y/%m/%d/'),
        ),
    ]
