# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaapi', '0003_weddingpicture_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingpicture',
            name='capture_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
