# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaapi', '0004_auto_20161023_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingpicture',
            name='thumbnail',
            field=models.ImageField(default='', editable=False, upload_to=b'weddingpictures/thumbs/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weddingpicture',
            name='picture',
            field=models.ImageField(upload_to=b'weddingpictures/full/%Y/%m/%d/'),
        ),
    ]
